### PR TITLE
Update logs

### PR DESCRIPTION
**Pull request by FERDIZ-afk**
## Your Pull Request Title
Pull request description. Describe what you changed or added here.

## Type
- [ ] New feature.
- [ ] Bug Fix.
- [x] Other:...

## Another details
- does this have anything to do with any of the issues? (if yes, tag the issue)

### CODE REVIEW

**Comment by JastinXyz** [comment]
bruh, doesn't it look too extravagant? added 1 package just to color text in console?

**Comment by JastinXyz** [comment]
ah

**Comment by JastinXyz** [comment]
its just 9KB

**Comment by FERDIZ-afk** [comment]
so that the console looks good, bro

**Comment by JastinXyz** [comment]
Merged! Thanks a lot!

**Pull request merged**
